package com.rkc.zds.resource.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * The persistent class for the PCM_CONTACT_ADDRESS database table.
 * 
 * 
 * CREATE TABLE Address (
  addrID     INTEGER PRIMARY KEY generated BY DEFAULT AS IDENTITY,
  addrStreet VARCHAR(50) NOT NULL,
  addrCity   VARCHAR(50) NOT NULL,
  addrState  CHAR(2)     NOT NULL,
  addrZip    CHAR(10)    NOT NULL
);
*/
@Entity
@Table(name="PCM_CONTACT_ADDRESS")
public class AddressEntity implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="ID")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer addressId;

	@Column(name="CONTACT_ID")
	private int contactId;

	@Column(name="ADDRESS_LINE_1")
	private String addressLine1;

	@Column(name="ADDRESS_LINE_2")
	private String addressLine2;
	
	@Column(name="ADDRESS_CITY")
	private String addressCity;	

	@Column(name="ADDRESS_STATE")
	private String addressState;	

	@Column(name="ADDRESS_COUNTRY")
	private String addressCountry;	
	
	@Column(name="ADDRESS_ZIP")
	private String addressZip;
	
	@Column(name="ADDRESS_KIND")
	private int addressKind;
	
	public Integer getAddressId() {
		return addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public int getContactId() {
		return contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public String getAddressLine1() {
		return addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getAddressCity() {
		return addressCity;
	}

	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity;
	}

	public String getAddressState() {
		return addressState;
	}

	public void setAddressState(String addressState) {
		this.addressState = addressState;
	}

	public String getAddressCountry() {
		return addressCountry;
	}

	public void setAddressCountry(String addressCountry) {
		this.addressCountry = addressCountry;
	}

	public String getAddressZip() {
		return addressZip;
	}

	public void setAddressZip(String addressZip) {
		this.addressZip = addressZip;
	}

	public int getAddressKind() {
		return addressKind;
	}

	public void setAddressKind(int addressKind) {
		this.addressKind = addressKind;
	}

	public AddressEntity() {
    }
}
    