package com.rkc.zds.resource.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PcmContacts generated by hbm2java
 */
@Entity
@Table(name = "PCM_CONTACTS")
public class ContactEntity implements java.io.Serializable {
	
    private static final long serialVersionUID = -6809049173391335091L;
	
	@Id
	@Column(name="CONTACT_ID", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer id;
	
	@Column(name = "USER_ID")	
	private Integer userId;

	@Column(name = "FIRSTNAME", nullable = false, length = 100)
	private String firstName;

	@Column(name = "LASTNAME", nullable = false, length = 100)
	private String lastName;

	@Column(name = "TITLE", length = 100)
	private String title;

	@Column(name = "COMPANY", length = 100)
	private String company;
	
	@Column(name = "IMAGE_URL", length = 100)
	private String imageURL;

	@Column(name = "SKYPE", length = 100)
	private String skype;

	@Column(name = "TWITTER", length = 100)
	private String twitter;

	@Column(name = "NOTES", length = 100)
	private String notes;
	
	@Column(name = "PRESENCE_IMAGE_URL", length = 100)
	private String presenceImageUrl;
	
	@Column(name="ENABLED")	
	private Integer enabled;

	public ContactEntity() {
	}

	public ContactEntity(int id, String firstName, String lastName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public ContactEntity(
			int id, 
			String firstName, 
			String lastName, 
			String title, 
			String company) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.title = title;
		this.company = company;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}
	
	public String getImageURL() {
		return imageURL;
	}

	public void setImageURL(String imageURL) {
		this.imageURL = imageURL;
	}

	public String getSkype() {
		return skype;
	}

	public void setSkype(String skype) {
		this.skype = skype;
	}

	public String getTwitter() {
		return twitter;
	}

	public void setTwitter(String twitter) {
		this.twitter = twitter;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getPresenceImageUrl() {
		return this.presenceImageUrl;
	}

	public void setPresenceImageUrl(String presenceImageUrl) {
		this.presenceImageUrl = presenceImageUrl;
	}

	public Integer getEnabled() {
		return enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

	@Override
	public int hashCode() {
	    int hash = 3;
	    hash = 53 * hash + (this.id);
	    return hash;
	}

	@Override
	public boolean equals(Object other) {
	    boolean result;
	    if((other == null) || (getClass() != other.getClass())){
	        result = false;
	    } // end if
	    else{
	        ContactEntity otherContact = (ContactEntity)other;
	        result = (id == (otherContact.id));
	    } // end else

	    return result;
	}

}
